# MongoDB Connection String
# format: mongodb://[username:password@]host[:port]/database
spring.data.mongodb.uri=mongodb://localhost:27017/todo_db

# Optional: Show MongoDB queries in the console (useful for debugging)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Optional: Port for your Spring Boot Application (default is 8080)
server.port=8080